### ISSUE TITLE
Did you solve this issue ?

### ISSUE THREAD

**Issue by JMacorighDefiInformatique** [moczix/angular-ssr-custom-router-ng0205-err#1]
Aloha ! 

I try to contact you because I saw your issue here : https://github.com/angular/angular/issues/45750
Today, I've exactly this error, NG0205 error on refresh and I dont know where it happens.
I dont extend the Router class like you but the error also come from the Router module.

Do you remember the solution if you found any?

Thanks a lot!

**Comment by moczix** [comment]
hello :P currently the best way is to update to ng15 and use inject()

but for previous versions i also managed to bypass the issue.
So you need to make constructor intact, and provide other "data" by use function like

public setSomething()

**Comment by JMacorighDefiInformatique** [comment]
Thanks a lot for your quick answer!
I'll try to upgrade to NG15 and see if the error persists and keep searching where I did things wrong :smile: 

Have a nice day !
